const INDIAN_BANKS = [
  // --- POPULAR / TOP BANKS ---
  {
    code: "SBI",
    name: "State Bank of India",
    shortName: "SBI",
    ifscPrefix: "SBIN",
    upiHandle: "oksbi",
    category: "POPULAR",
    brandColor: "#006699",
    accentColor: "#280071",
    tagline: "The Banker to Every Indian",
    popular: true,
  },
  {
    code: "HDFC",
    name: "HDFC Bank",
    shortName: "HDFC",
    ifscPrefix: "HDFC",
    upiHandle: "okhdfcbank",
    category: "POPULAR",
    brandColor: "#004c8f",
    accentColor: "#ed232a",
    tagline: "We Understand Your World",
    popular: true,
  },
  {
    code: "ICICI",
    name: "ICICI Bank",
    shortName: "ICICI",
    ifscPrefix: "ICIC",
    upiHandle: "okicici",
    category: "POPULAR",
    brandColor: "#f37021",
    accentColor: "#a32020",
    tagline: "Hum Hai Na, Khayal Aapka",
    popular: true,
  },
  {
    code: "AXIS",
    name: "Axis Bank",
    shortName: "Axis",
    ifscPrefix: "UTIB",
    upiHandle: "okaxis",
    category: "POPULAR",
    brandColor: "#97144d",
    accentColor: "#ed1c24",
    tagline: "Badhti Ka Naam Zindagi",
    popular: true,
  },
  {
    code: "KOTAK",
    name: "Kotak Mahindra Bank",
    shortName: "Kotak",
    ifscPrefix: "KKBK",
    upiHandle: "okkotak",
    category: "POPULAR",
    brandColor: "#ed1c24",
    accentColor: "#003366",
    tagline: "Let's Make Money Simple",
    popular: true,
  },
  {
    code: "PNB",
    name: "Punjab National Bank",
    shortName: "PNB",
    ifscPrefix: "PUNB",
    upiHandle: "okpnb",
    category: "POPULAR",
    brandColor: "#a20b2d",
    accentColor: "#f39200",
    tagline: "The Name You Can Bank Upon",
    popular: true,
  },
  {
    code: "BOB",
    name: "Bank of Baroda",
    shortName: "Baroda",
    ifscPrefix: "BARB",
    upiHandle: "okbob",
    category: "POPULAR",
    brandColor: "#f26522",
    accentColor: "#004a80",
    tagline: "India's International Bank",
    popular: true,
  },

  // --- PUBLIC SECTOR BANKS ---
  {
    code: "CANARA",
    name: "Canara Bank",
    shortName: "Canara",
    ifscPrefix: "CNRB",
    upiHandle: "okcanara",
    category: "PUBLIC",
    brandColor: "#008ece",
    accentColor: "#ffd200",
    tagline: "Together We Can",
    popular: false,
  },
  {
    code: "UNION",
    name: "Union Bank of India",
    shortName: "Union Bank",
    ifscPrefix: "UBIN",
    upiHandle: "okunion",
    category: "PUBLIC",
    brandColor: "#005a9c",
    accentColor: "#e31b23",
    tagline: "Good People to Bank With",
    popular: false,
  },
  {
    code: "INDIAN",
    name: "Indian Bank",
    shortName: "Indian Bank",
    ifscPrefix: "IDIB",
    upiHandle: "okindianbank",
    category: "PUBLIC",
    brandColor: "#003a70",
    accentColor: "#e31e24",
    tagline: "Your Tech-Friendly Bank",
    popular: false,
  },
  {
    code: "BOI",
    name: "Bank of India",
    shortName: "BOI",
    ifscPrefix: "BKID",
    upiHandle: "okboi",
    category: "PUBLIC",
    brandColor: "#e65100",
    accentColor: "#1565c0",
    tagline: "Relationship Beyond Banking",
    popular: false,
  },
  {
    code: "CENTRAL",
    name: "Central Bank of India",
    shortName: "Central Bank",
    ifscPrefix: "CBIN",
    upiHandle: "okcbi",
    category: "PUBLIC",
    brandColor: "#003b70",
    accentColor: "#d32f2f",
    tagline: "Central to You Since 1911",
    popular: false,
  },
  {
    code: "IOB",
    name: "Indian Overseas Bank",
    shortName: "IOB",
    ifscPrefix: "IOBA",
    upiHandle: "okiob",
    category: "PUBLIC",
    brandColor: "#005691",
    accentColor: "#ffcc00",
    tagline: "Good People to Grow With",
    popular: false,
  },
  {
    code: "UCO",
    name: "UCO Bank",
    shortName: "UCO Bank",
    ifscPrefix: "UCBA",
    upiHandle: "okuco",
    category: "PUBLIC",
    brandColor: "#0288d1",
    accentColor: "#f57c00",
    tagline: "Honours Your Trust",
    popular: false,
  },
  {
    code: "MAHA",
    name: "Bank of Maharashtra",
    shortName: "Maharashtra",
    ifscPrefix: "MAHB",
    upiHandle: "okmahb",
    category: "PUBLIC",
    brandColor: "#00838f",
    accentColor: "#e65100",
    tagline: "One Family One Bank",
    popular: false,
  },
  {
    code: "PSB",
    name: "Punjab & Sind Bank",
    shortName: "Punjab & Sind",
    ifscPrefix: "PSIB",
    upiHandle: "okpsb",
    category: "PUBLIC",
    brandColor: "#2e7d32",
    accentColor: "#fbc02d",
    tagline: "Where Service Is A Way Of Life",
    popular: false,
  },

  // --- PRIVATE SECTOR BANKS ---
  {
    code: "INDUSIND",
    name: "IndusInd Bank",
    shortName: "IndusInd",
    ifscPrefix: "INDB",
    upiHandle: "okindus",
    category: "PRIVATE",
    brandColor: "#8b1820",
    accentColor: "#ff9933",
    tagline: "We Make You Feel Richer",
    popular: true,
  },
  {
    code: "IDFC",
    name: "IDFC FIRST Bank",
    shortName: "IDFC FIRST",
    ifscPrefix: "IDFB",
    upiHandle: "okidfc",
    category: "PRIVATE",
    brandColor: "#9e1b32",
    accentColor: "#ffbf00",
    tagline: "Always You First",
    popular: true,
  },
  {
    code: "FEDERAL",
    name: "Federal Bank",
    shortName: "Federal",
    ifscPrefix: "FDRL",
    upiHandle: "okfederal",
    category: "PRIVATE",
    brandColor: "#003b7a",
    accentColor: "#ffcc00",
    tagline: "Your Perfect Banking Partner",
    popular: false,
  },
  {
    code: "YES",
    name: "Yes Bank",
    shortName: "Yes Bank",
    ifscPrefix: "YESB",
    upiHandle: "okyes",
    category: "PRIVATE",
    brandColor: "#004a8f",
    accentColor: "#ed1c24",
    tagline: "Experience Our Expertise",
    popular: false,
  },
  {
    code: "SOUTHINDIAN",
    name: "South Indian Bank",
    shortName: "South Indian",
    ifscPrefix: "SIBL",
    upiHandle: "oksib",
    category: "PRIVATE",
    brandColor: "#c8102e",
    accentColor: "#00205b",
    tagline: "Experience Next Generation Banking",
    popular: false,
  },
  {
    code: "RBL",
    name: "RBL Bank",
    shortName: "RBL",
    ifscPrefix: "RATN",
    upiHandle: "okrbl",
    category: "PRIVATE",
    brandColor: "#003366",
    accentColor: "#e31837",
    tagline: "Apno Ka Bank",
    popular: false,
  },
  {
    code: "BANDHAN",
    name: "Bandhan Bank",
    shortName: "Bandhan",
    ifscPrefix: "BDBL",
    upiHandle: "okbandhan",
    category: "PRIVATE",
    brandColor: "#a31d24",
    accentColor: "#ffc20e",
    tagline: "Aapka Bhala, Sabki Bhalai",
    popular: false,
  },
  {
    code: "CITYUNION",
    name: "City Union Bank",
    shortName: "City Union",
    ifscPrefix: "CIUB",
    upiHandle: "okcub",
    category: "PRIVATE",
    brandColor: "#00529b",
    accentColor: "#f37021",
    tagline: "Trust and Excellence Since 1904",
    popular: false,
  },
  {
    code: "JK",
    name: "Jammu & Kashmir Bank",
    shortName: "J&K Bank",
    ifscPrefix: "JAKA",
    upiHandle: "okjk",
    category: "PRIVATE",
    brandColor: "#004b87",
    accentColor: "#d9232a",
    tagline: "Serving to Empower",
    popular: false,
  },
  {
    code: "KARNATAKA",
    name: "Karnataka Bank",
    shortName: "Karnataka Bank",
    ifscPrefix: "KARB",
    upiHandle: "okkbl",
    category: "PRIVATE",
    brandColor: "#b81c24",
    accentColor: "#003366",
    tagline: "Your Family Bank Across India",
    popular: false,
  },
  {
    code: "KVB",
    name: "Karur Vysya Bank",
    shortName: "KVB",
    ifscPrefix: "KVBL",
    upiHandle: "okkvb",
    category: "PRIVATE",
    brandColor: "#9c27b0",
    accentColor: "#ff9800",
    tagline: "Smart Way to Bank",
    popular: false,
  },
  {
    code: "TMB",
    name: "Tamilnad Mercantile Bank",
    shortName: "TMB",
    ifscPrefix: "TMBL",
    upiHandle: "oktmb",
    category: "PRIVATE",
    brandColor: "#0277bd",
    accentColor: "#f57f17",
    tagline: "Step Ahead With TMB",
    popular: false,
  },

  // --- PAYMENTS & SMALL FINANCE BANKS ---
  {
    code: "AIRTEL",
    name: "Airtel Payments Bank",
    shortName: "Airtel Bank",
    ifscPrefix: "AIRP",
    upiHandle: "airtel",
    category: "PAYMENTS_SFB",
    brandColor: "#e40000",
    accentColor: "#ffffff",
    tagline: "Banking Is Now At Your Fingertips",
    popular: true,
  },
  {
    code: "IPPB",
    name: "India Post Payments Bank",
    shortName: "IPPB",
    ifscPrefix: "IPOS",
    upiHandle: "postbank",
    category: "PAYMENTS_SFB",
    brandColor: "#b71c1c",
    accentColor: "#fbc02d",
    tagline: "Aapka Bank, Aapke Dwaar",
    popular: true,
  },
  {
    code: "PAYTM",
    name: "Paytm Payments Bank",
    shortName: "Paytm Bank",
    ifscPrefix: "PYTM",
    upiHandle: "paytm",
    category: "PAYMENTS_SFB",
    brandColor: "#00b9f1",
    accentColor: "#002e6e",
    tagline: "India's Most Trusted Digital Bank",
    popular: true,
  },
  {
    code: "AU",
    name: "AU Small Finance Bank",
    shortName: "AU Small Finance",
    ifscPrefix: "AUBL",
    upiHandle: "okau",
    category: "PAYMENTS_SFB",
    brandColor: "#6c2b8c",
    accentColor: "#ff6f00",
    tagline: "Badlaav Humse Hai",
    popular: false,
  },
  {
    code: "EQUITAS",
    name: "Equitas Small Finance Bank",
    shortName: "Equitas SFB",
    ifscPrefix: "ESFB",
    upiHandle: "okequitas",
    category: "PAYMENTS_SFB",
    brandColor: "#006837",
    accentColor: "#f15a24",
    tagline: "It's Fun Banking",
    popular: false,
  },
  {
    code: "UJJIVAN",
    name: "Ujjivan Small Finance Bank",
    shortName: "Ujjivan SFB",
    ifscPrefix: "UJVN",
    upiHandle: "okujjivan",
    category: "PAYMENTS_SFB",
    brandColor: "#1b5e20",
    accentColor: "#ff9100",
    tagline: "Build a Better Life",
    popular: false,
  },
  {
    code: "JANA",
    name: "Jana Small Finance Bank",
    shortName: "Jana SFB",
    ifscPrefix: "JSFB",
    upiHandle: "okjana",
    category: "PAYMENTS_SFB",
    brandColor: "#0d47a1",
    accentColor: "#ff3d00",
    tagline: "Likho Apni Kahaani",
    popular: false,
  },
];

module.exports = {
  INDIAN_BANKS,
};
